batch_size: 4
iters: 160000

train_dataset:
  type: Dataset
  dataset_root: /mnt/DATA/tesi/dataset/dataset_paddleseg/
  train_path: /mnt/DATA/tesi/dataset/dataset_paddleseg/train.txt
  num_classes: 2
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [820, 410] # [0.8 * 1024, 0.8 * 512]
    - type: RandomPaddingCrop
      crop_size: [820, 410]
    - type: RandomPaddingCrop
      crop_size: [820, 410]
    - type: RandomPaddingCrop
      crop_size: [820, 410]
    - type: RandomPaddingCrop
      crop_size: [820, 410]
    - type: RandomPaddingCrop
      crop_size: [820, 410]
    - type: RandomPaddingCrop
      crop_size: [820, 410]
    - type: RandomPaddingCrop
      crop_size: [820, 410]
    - type: RandomPaddingCrop
      crop_size: [820, 410]
    - type: RandomPaddingCrop
      crop_size: [820, 410]
    - type: RandomHorizontalFlip
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: /mnt/DATA/tesi/dataset/dataset_paddleseg/
  val_path: /mnt/DATA/tesi/dataset/dataset_paddleseg/val.txt
  num_classes: 2
  mode: val
  transforms:
    - type: Normalize

test_config:
  aug_eval: True
  scales: 1.0

loss:
  types:
    - type: CrossEntropyLoss
      weight: [0.8, 0.2]
    - type: CrossEntropyLoss
      weight: [0.8, 0.2]
    - type: CrossEntropyLoss
      weight: [0.8, 0.2]
  coef: [1, 1, 1]

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 5.0e-4

lr_scheduler:
  type: PolynomialDecay
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5
  learning_rate: 0.005
  end_lr: 0
  power: 0.9

model:
  type: PPLiteSeg
  num_classes: 2
  backbone:
    type: STDC1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 128]
